### ISSUE TITLE
the p2tr address seems wrong.

### ISSUE THREAD

**Issue by betta-cyber** [10gic/btc-address-dump#10]
when i run 
```
btc_address_dump -d bip86 --taproot-output-pubkey 0x4a6f5e3a0dc3a293d0938ef6d7d91cba8bc7615f0107963333320534c2cde210
taproot output pubkey = 4a6f5e3a0dc3a293d0938ef6d7d91cba8bc7615f0107963333320534c2cde210
bech32m address (p2tr) = bc1pffh4uwsdcw3f85yn3mmd0kguh29uwc2lqyrevvenxgznfskduggq04scrt
```
the p2tr address seems wrong.

**Comment by 10gic** [comment]
What is the correct address you expect?

**Comment by 10gic** [comment]
You can verify it in https://slowli.github.io/bech32-buffer/

<img width="1059" alt="image" src="https://github.com/10gic/btc-address-dump/assets/2391796/0f67f098-6f50-4276-93b9-264980707bad">
