### ISSUE TITLE
Can you this tool with btc forked coin ?

### ISSUE THREAD

**Issue by odomdev** [10gic/btc-address-dump#3]
Can you this tool with forked coin from BTC ?

**Comment by 10gic** [comment]
Currently, LTC is supported.

**Comment by Justin11111a** [comment]
when we use this tool ?

**Comment by odomdev** [comment]
when can use this tool ?

**Comment by 10gic** [comment]
Already upload to pypi, you can install it by `pip3 install -U btc-address-dump`.

Here is an example about ltc:
```
$ btc_address_dump -c ltc 6vP4eghhU3Gs8S1hgk2XNgD319ctMXzTZsWW8wLjEDjLHjyahvu
private key (hex) = a5db75d914f69dbfe2edef6c505cd21071711ffe0f7eeee3c7349691a24028ad
private key (WIF) = 6vP4eghhU3Gs8S1hgk2XNgD319ctMXzTZsWW8wLjEDjLHjyahvu
private key (WIF compressed) = T8cP7LEdcM32FoQ6aQuj4g47qf3PfdncG5wDc2r5PMBr8tYRCZU8
public key (uncompressed) = 045172d0a472f5943716bd1e6fcb13c6932f6add5ae32360ae2f374755c30b729098870b022b89bce1f544ed9cc3d1eebb7439dbebea9a0ae42f1808ab4c509ea8
public key (compressed) = 025172d0a472f5943716bd1e6fcb13c6932f6add5ae32360ae2f374755c30b7290
hash160 of uncompressed public key = f140de3d8c5d59f298f34778b2cdcbc56345b601
hash160 of compressed public key = 916eea42bfa275cc6a55168b0e6f2aac1784dee0
legacy address (p2pkh uncompressed) = LhDapZU7HLJDm5e5DBPmwFpNsvijsRiUa7
legacy address (p2pkh compressed) = LYUw7YU6ztGo2Jnws9AbH7PMBdkv5ocDke
p2sh-segwit address (p2sh p2wpkh) = MBEdkEujMnRYwRjp2goZDJD5YEVnytLKv1
bech32 address (p2wpkh) = ltc1qj9hw5s4l5f6uc6j4z69sume24stcfhhqrs62wj
```

**Comment by odomdev** [comment]
how about other new coin ? how to use it ?

**Comment by 10gic** [comment]
Other coins are not supported currently.

**Comment by odomdev** [comment]
if other coin cloned from Bitcoin  can use it ?

**Comment by 10gic** [comment]
It's easy to enhance this tool for other bitcoin fork chains. Just like it supports litecoin: https://github.com/10gic/btc-address-dump/blob/99a78f51f96dafd7b2b94756e854030aa112da70/btc_address_dump/btc_address_dump.py#L67

**Comment by odomdev** [comment]
ok I understand. can I send you a pull request to add new coin ?

**Comment by 10gic** [comment]
Sure, pull requests are welcome.

**Comment by odomdev** [comment]
ok I will friend to do it.

**Comment by 10gic** [comment]
Now, Bitcoin forks can be supported by just changing https://github.com/10gic/btc-address-dump/blob/main/btc_address_dump/coins.yaml
