### ISSUE TITLE
command compile and dependency installation command

### ISSUE THREAD

**Issue by odomdev** [10gic/btc-address-dump#5]
can provide the command of compile and install dependency ?

**Comment by 10gic** [comment]
Dependences will be auto installed by `pip3 install btc-address-dump`. If you meet permission issue, you can run `sudo pip3 install btc-address-dump` or `pip3 install --user btc-address-dump`.

**Comment by odomdev** [comment]
cd btc-address-dump
pip3 install btc-address-dump

btc_address_dump c7ac679b56f50bfd54dd924fe45a8dca7a1c2dced254b03dac22afc03adb9127

Traceback (most recent call last):
  File "/usr/local/bin/btc_address_dump", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.7/dist-packages/btc_address_dump/__init__.py", line 10, in run_main
    main_entry(sys.argv)
  File "/usr/local/lib/python3.7/dist-packages/btc_address_dump/btc_address_dump.py", line 51, in main_entry
    coins_info = yaml.load(file_data, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'

**Comment by 10gic** [comment]
This issue has actually fixed in 0.2.8 (rather than 0.2.7) btc-address-dump, sorry for this inconvenience.

**Comment by odomdev** [comment]
still error
root@ELECT02-UBUN18:~/btc-address-dump# sudo pip3 install btc-address-dump

Requirement already satisfied: btc-address-dump in /usr/local/lib/python3.7/dist-packages (0.2.5)
Requirement already satisfied: base58 in /usr/local/lib/python3.7/dist-packages (from btc-address-dump) (2.1.0)
Requirement already satisfied: ecdsa in /usr/local/lib/python3.7/dist-packages (from btc-address-dump) (0.16.1)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from ecdsa->btc-address-dump) (1.11.0)
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv

root@ELECT02-UBUN18:~/btc-address-dump# btc_address_dump c7ac679b56f50bfd54dd924fe45a8dca7a1c2dced254b03dac22afc03adb9127
Traceback (most recent call last):
  File "/usr/local/bin/btc_address_dump", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.7/dist-packages/btc_address_dump/__init__.py", line 10, in run_main
    main_entry(sys.argv)
  File "/usr/local/lib/python3.7/dist-packages/btc_address_dump/btc_address_dump.py", line 51, in main_entry
    coins_info = yaml.load(file_data, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'

**Comment by 10gic** [comment]
> still error
> root@ELECT02-UBUN18:~/btc-address-dump# sudo pip3 install btc-address-dump
> 
> Requirement already satisfied: btc-address-dump in /usr/local/lib/python3.7/dist-packages (0.2.5)
> Requirement already satisfied: base58 in /usr/local/lib/python3.7/dist-packages (from btc-address-dump) (2.1.0)
> Requirement already satisfied: ecdsa in /usr/local/lib/python3.7/dist-packages (from btc-address-dump) (0.16.1)
> Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from ecdsa->btc-address-dump) (1.11.0)
> WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
> 
> root@ELECT02-UBUN18:~/btc-address-dump# btc_address_dump c7ac679b56f50bfd54dd924fe45a8dca7a1c2dced254b03dac22afc03adb9127
> Traceback (most recent call last):
> File "/usr/local/bin/btc_address_dump", line 8, in
> sys.exit(run_main())
> File "/usr/local/lib/python3.7/dist-packages/btc_address_dump/**init**.py", line 10, in run_main
> main_entry(sys.argv)
> File "/usr/local/lib/python3.7/dist-packages/btc_address_dump/btc_address_dump.py", line 51, in main_entry
> coins_info = yaml.load(file_data, Loader=yaml.FullLoader)
> AttributeError: module 'yaml' has no attribute 'FullLoader'

Which version is installed? It seams not version 0.2.8.

Please help to check the version:
```
$ ls -l /home/user1/.local/lib/python3.6/site-packages/    # In you env, may be change to /usr/local/lib/python3.7/dist-packages/btc_address_dump/
total 80K
drwxrwxr-x. 3 user1 4.0K May  8 05:56 base58/
drwxrwxr-x. 2 user1 4.0K May  8 05:56 base58-2.1.0.dist-info/
drwxrwxr-x. 3 user1 4.0K May  8 07:30 btc_address_dump/
drwxrwxr-x. 2 user1 4.0K May  8 07:30 btc_address_dump-0.2.8.dist-info/       <----- 0.2.8
drwxrwxr-x. 3 user1 4.0K May  8 05:56 ecdsa/
drwxrwxr-x. 2 user1 4.0K May  8 05:56 ecdsa-0.16.1.dist-info/
drwxrwxr-x. 2 user1 4.0K May  8 05:56 __pycache__/
drwxrwxr-x. 2 user1 4.0K May  8 07:30 PyYAML-5.4.1.dist-info/
drwxrwxr-x. 2 user1 4.0K May  8 05:56 six-1.16.0.dist-info/
drwxrwxr-x. 3 user1 4.0K May  8 07:30 yaml/
drwxrwxr-x. 3 user1 4.0K May  8 07:30 _yaml/
-rw-rw-r--. 1 user1  34K May  8 05:56 six.py
```

**Comment by 10gic** [comment]
The version also display when installing
```
$ pip3 uninstall btc-address-dump
$ pip3 install btc-address-dump
Collecting btc-address-dump
  Downloading btc_address_dump-0.2.8-py2.py3-none-any.whl (14 kB)          <- 0.2.8
```

**Comment by odomdev** [comment]
root@ELECT02-UBUN18:~# pip3 install btc-address-dump
Requirement already satisfied: btc-address-dump in /usr/local/lib/python3.7/dist-packages (0.2.5)
Requirement already satisfied: ecdsa in /usr/local/lib/python3.7/dist-packages (from btc-address-dump) (0.16.1)
Requirement already satisfied: base58 in /usr/local/lib/python3.7/dist-packages (from btc-address-dump) (2.1.0)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from ecdsa->btc-address-dump) (1.11.0)
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv

**Comment by 10gic** [comment]
> pip3 install btc-address-dump
> Requirement already satisfied: btc-address-dump in /usr/local/lib/python3.7/dist-packages (0.2.5)
> Requirement already satisfied: ecdsa in /usr/local/lib/python3.7/dist-packages (from btc-address-dump) (0.16.1)
> Requirement already satisfied: base58 in /usr/local/lib/python3.7/dist-packages (from btc-address-dump) (2.1.0)
> Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from ecdsa->btc-address-dump) (1.11.0)
> WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv

May be the cache is used. Try uninstall it firstly, then install it by disabling cache.
```
pip3 uninstall btc-address-dump
pip3 install --no-cache-dir btc-address-dump
```

**Comment by odomdev** [comment]
ok thank it is working now.
